version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend_image
    container_name: library_backend
    build:
      context: .
      dockerfile: ./OnlineLibraryAPI/OnlineLibraryAPI.Presentation/Dockerfile

  client:
    image: ${DOCKER_REGISTRY-}client_image
    container_name: library_client
    build:
      context: ./OnlineLibraryWeb/online-library-web
      dockerfile: Dockerfile
    depends_on:
      - backend

  proxy:  
    image: nginx:mainline
    container_name: library_proxy
    depends_on:
      - backend
      - client